### ISSUE TITLE
rsound/draw: enabling drawing on user provided frame%

### ISSUE THREAD

**Issue by tiago4orion** [jbclements/RSound#36]
I'm writing a software to inspect/analyze sounds from speech and I would like to draw the waveforms/fft in my own frame (instead of creating a new one).

I've made a change in the library to achieve what I want, but let me know if this is already supported in other way (I'm new to racket). The changes I made are here:
https://github.com/NeowayLabs/RSound/commit/0f59f372cd9d56352e68d8787d7b26c533817723

Thanks for the awesome library =)

**Comment by jbclements** [comment]
> On Nov 1, 2017, at 18:20, Tiago Natel de Moura <notifications@github.com> wrote:
> 
> I'm writing a software to inspect/analyze sounds from speech and I would like to draw the waveforms/fft in my own frame (instead of creating a new one).
> 
> I've made a change in the library to achieve what I want, but let me know if this is already supported in other way (I'm new to racket). The changes I made are here:
> NeowayLabs/RSound@0f59f37

Looks like a good idea.

1) I see there are about five calls to vector-display-frame, and it looks to me like they all need to change, no?

2) After you do this, you should use the GitHub interface to issue a “pull request” against my repo. Let me know if you can’t figure out how to do this.

Thanks for your work!

John Clements

**Comment by tiago4orion** [comment]
closed by #37
