### ISSUE TITLE
Weird interaction with racket-chipmunk

### ISSUE THREAD

**Issue by srfoster** [jbclements/RSound#38]
Hi,

I just released some updated Racket bindings for Chipmunk:

https://github.com/thoughtstem/racket-chipmunk

I'm using racket-chipmunk and rsound together to make games, but for some reason racket-chipmunk seems to break rsound on Linux.  I don't even know why that would be, but here are the steps that I've used reproduce the issue:

1) Installed rsound
2) Installed racket-chipmunk
3) Wrote a super simple program that just requires rsound.  Ran it.  Everything was fine.
4) Added a require for racket-chipmunk before the rsound require.  Ran it.  Got an error ``Assertion #<procedure:negative?> failed on 0.0`` on the rsound require.  The stacktrack bottoms out somewhere in "pkgs/math-lib/math/private/flonum/flonum-constants.rkt".  No line number given.  
5) What's weird is that at this point, even if I *remove* the require for racket-chipmunk, I get the same error whenever I require rsound.  The problem persists until I restart DrRacket.

Feels funny.  I don't know why these packages would interact weirdly with each other.  And I've never seen something break in this way before.  Any pointers?

(Both packages use the Racket ffi, which I suspect might be relevant.   But I'm not sure.)

**Comment by jbclements** [comment]
Need more details. What platform? What program? I just tried this program:

```racket
#lang racket

(require racket-chipmunk)
(require rsound)
```

on OS X and it appeared to finish fine at the command line.

**Comment by srfoster** [comment]
I should mention that I've managed to fix this -- apparently just by recompiling the chipmunk binaries.  I'm not sure WHY that fixed it, but I do have a working rsound-based system in my game-engine now.

Thanks again for making this package!

**Comment by jbclements** [comment]
Very glad to hear it. 

John
