### ISSUE TITLE
Cannot install rsound because of portaudio version specification

### ISSUE THREAD

**Issue by a29gh** [jbclements/RSound#44]
Installation of rsound using raco is failing because it is not liking portaudio's version specification.

$ raco pkg install rsound
Resolving "rsound" via https://download.racket-lang.org/releases/7.7/catalog/
Resolving "rsound" via https://pkgs.racket-lang.org
Using cached15910681631591068163562 for github://github.com/jbclements/RSound/master/
The following uninstalled packages are listed as dependencies of rsound:
   portaudio
   memoize
Would you like to install these dependencies? [Y/n/a/c/?] Y
00: Resolving "portaudio" via https://download.racket-lang.org/releases/7.7/catalog/
00: Resolving "portaudio" via https://pkgs.racket-lang.org
Resolving "memoize" via https://download.racket-lang.org/releases/7.7/catalog/
Resolving "memoize" via https://pkgs.racket-lang.org
Using cached15911164011591116401066 for github://github.com/jbclements/portaudio/master/
Using cached15911164021591116402148 for github://github.com/jbclements/memoize/master
pkg: bad version specification for portaudio: "2020-05-29"
raco pkg install: version mismatch for dependency
  for package: rsound
  mismatch packages:
   portaudio (have 0.0, need 0.1)

**Comment by jbclements** [comment]
ouch... I don't have time to take a look at this for a day or two. It looks to me like an easy fix...

**Comment by jbclements** [comment]
Huh. Actually, I'm not sure what would cause this. Did you solve this problem? I mean, I know it was like 2 years ago...

**Comment by a29gh** [comment]
John Clements ***@***.***> writes:

> [1:text/plain Hide]
>
> Huh. Actually, I'm not sure what would cause this. Did you solve this problem? I mean, I know it was like 2 years ago...

I remember I did write some programs with your rsound module... I must have done something. Or maybe I got this error when trying to update to a later version? I'm sorry, I just don't remember any more and am no longer using racket. -A

**Comment by jbclements** [comment]
No problem! Many thanks for your fast response. I'm going to close this issue.
