### ISSUE TITLE
Don't hear any sound

### ISSUE THREAD

**Issue by wanderley** [jbclements/RSound#48]
**Configuration**
- DrRacket, version 8.3 (f54d4eb5018fd19135fee2886e56dba8bc496ea345776cacf748cc0ec49a9e68)
- macOS Monterey 12.0.1
- rsound installed via Package Manager

**Problem**
With this configuration, I can't hear anything when I execute the following code
```
#lang racket
(require rsound)
(play ding)
```

**Comment by jbclements** [comment]
Is this an M1 machine, or an Intel machine?

**Comment by wanderley** [comment]
It is an Intel machine.

- MacBook Pro (16-inch, 2019)
- 2.4 GHz 8-Core Intel Core i9
- 32 GB 2667 MHz DDR4


On Mon, Dec 13, 2021 at 8:05 AM John Clements ***@***.***> wrote:
>
> Is this an M1 machine, or an Intel machine?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Wanderley Guimarães

**Comment by wanderley** [comment]
The issue was gone after restarting the computer.

**Comment by wanderley** [comment]
I discovered what is happening.  I have to use `set-output-device!` when using Headset, even when I run the program using the Headset as my main output device.

**Comment by jbclements** [comment]
Ah! That makes sense. 

John
